name: Deploy Java project to Azure

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'intregrations' 
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Project
        run: mvn -B clean package -DskipTests

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: springboot-example
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: springboot-example

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '*.jar'

